#!/bin/bash

# Nginx setup for mikroimathites.gr
# Writes the canonical config (see docs/nginx-nextjs-config.md) and enables it.
#
# IMPORTANT: the config file is sites-available/mikroimathites.conf — there must be
# exactly ONE enabled file with these server_names. A previous version of this
# script wrote a second file ("mikroimathites") whose port-80 proxy shadowed the
# HTTPS redirect for months (fixed 2026-07-08).
#
# Requires an existing Let's Encrypt cert for mikroimathites.gr + www
# (certbot certonly --webroot -w /var/www/certbot -d mikroimathites.gr -d www.mikroimathites.gr)

set -e

echo "🚀 Setting up Nginx for mikroimathites.gr..."

# Install nginx if not installed
if ! command -v nginx &> /dev/null; then
    echo "📦 Installing Nginx..."
    apt update
    apt install -y nginx
fi

cat > /etc/nginx/sites-available/mikroimathites.conf << 'EOF'
# mikroimathites.gr — canonical host: https://mikroimathites.gr
# Generated by scripts/nginx-setup.sh; documented in docs/nginx-nextjs-config.md

# HTTP (both hosts): ACME challenge + redirect everything else to https apex
server {
  listen 80;
  server_name mikroimathites.gr www.mikroimathites.gr;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://mikroimathites.gr$request_uri;
  }
}

# HTTPS www -> apex
server {
  listen 443 ssl http2;
  server_name www.mikroimathites.gr;

  ssl_certificate /etc/letsencrypt/live/mikroimathites.gr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mikroimathites.gr/privkey.pem;

  return 301 https://mikroimathites.gr$request_uri;
}

# HTTPS apex: main site
server {
  listen 443 ssl http2;
  server_name mikroimathites.gr;

  ssl_certificate /etc/letsencrypt/live/mikroimathites.gr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/mikroimathites.gr/privkey.pem;

  # Security headers
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-XSS-Protection "1; mode=block" always;

  # Gzip compression
  gzip on;
  gzip_vary on;
  gzip_min_length 1024;
  gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;

  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
EOF

# Enable the site, and remove configs that would shadow it
ln -sf /etc/nginx/sites-available/mikroimathites.conf /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
rm -f /etc/nginx/sites-enabled/mikroimathites  # legacy file, see header comment

# Test before reload — abort on failure (set -e)
nginx -t

systemctl reload nginx
systemctl enable nginx

echo "✅ Nginx setup complete!"
echo "🌐 Canonical host: https://mikroimathites.gr (all other variants 301 there)"
